---

networks:
  proxy:
    attachable: true
    driver: overlay
    external: true
#volumes:
  #python-libs:

services:
  vscode-tunnel:
    user: code:src
    image: i8degrees/vscode-server:latest
    build:
      context: .
      dockerfile: "Dockerfile"
    command: ["tunnel"]
    restart: unless-stopped
    container_name: vscode-tunnel-1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- /etc/ssl/certs:/etc/ssl/certs:ro
      # NOTE(JEFF): This is a "bind mount" and is read just as port bindings 
      # are: external path:container path. In this case, "./mounts/Projects"
      # is a symbolic link one directory deep from this project root that 
      # is linked inside the container at /home/code/Projects.
      - "./mounts/Projects:/home/code/Projects:ro"
    env_file:
      ".env"
    networks:
      - proxy
    #expose:
    # external port:container port
    ports:
      # NOTE(JEFF): For use with "code tunnel" feature; the default port is
      # 8000 (container) and has been externally bound at port 8010.
      #- "8010:8000/tcp"
      - "${VSCODE_EXTERNAL_CODE_TUNNEL_PORT:-8010}:8000/tcp"

  vscode-web:
    user: code:src
    image: i8degrees/vscode-server:latest
    build:
      context: .
      dockerfile: "Dockerfile"
    #"${VSCODE_EXTERNAL_CODE_WEB_PORT:-8020}"
    # TODO(JEFF): Append ${VSCODE_EXTERNAL_CODE_WEB_HOST} after --host element
    command: [
      "serve-web",
      "--host",
      "0.0.0.0",
      # NOTE(JEFF): This is the container's port
      "--port",
      "80"
    ]
    restart: unless-stopped
    container_name: vscode-web-1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- /etc/ssl/certs:/etc/ssl/certs:ro
      # NOTE(JEFF): This is a "bind mount" and is read just as port bindings 
      # are: external path:container path. In this case, "./mounts/Projects"
      # is a symbolic link one directory deep from this project root that 
      # is linked inside the container at /home/code/Projects.
      - "./mounts/Projects:/home/code/Projects:ro"
    env_file:
      ".env"
    networks:
      - proxy
    #expose:
    # external port:container port
    ports:
      # NOTE(JEFF): The "command" service attribute specified above is what
      # leads to the container setting up the web server at the configured
      # port given (80).
      #
      # IMPORTANT(JEFF): The external binding port (left-most number) is what
      # your host machine sees and thus is how you access the container. If 
      # I were interested in port forwarding this service through a gateway 
      # router -- to share with friends -- the internal IP and port would be:
      # scorpio.home:8020 -> WAN_IP:80.
      #
      # One last thing regarding your external port assignment: whichever port
      # you pick must be unused (unbinded) by any other service, Docker or
      # otherwise! You will see an error message telling you about this if you
      # fail to select an unused port. You should typically try picking one
      # that does not require elevated privileges -- unused port number > 1024.
      #- "8020:80/tcp"
      - "${VSCODE_EXTERNAL_CODE_WEB_PORT:-8020}:80/tcp"


